# Generated by Django 4.1 on 2022-09-10 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('hatch_date', models.DateField(max_length=50)),
                ('diet', models.ManyToManyField(to='reptilerepoapi.diet')),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptilerepoapi.lister')),
            ],
        ),
        migrations.CreateModel(
            name='Morph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Morph', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReptileDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptilerepoapi.diet')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptilerepoapi.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='morph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptilerepoapi.morph'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptilerepoapi.sex'),
        ),
        migrations.AddField(
            model_name='listing',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptilerepoapi.species'),
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('publishing_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptilerepoapi.lister')),
            ],
        ),
    ]
