# Generated by Django 4.1 on 2022-08-29 22:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reptilerepoapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lister',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 8, 29, 22, 1, 46, 190825, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=50)),
                ('morph', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('hatch_date', models.DateField(max_length=50)),
                ('diet', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptilerepoapi.lister')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptilerepoapi.species')),
            ],
        ),
    ]
